on:
  push:
    branches:
    - main
    - master

steps:
   - uses: docker/build-push-action@v1
     name: Build & push Docker image
     with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pontostroy/web-render
        tag_with_ref: true
        tag_with_sha: true
