on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
          name: Check out code
        - uses: ricardochaves/python-lint@v1.3.0
          name: tests
          with:
            python-root-list: "tests"
            use-pylint: true
            use-pycodestyle: false
            use-flake8: true
            use-black: true
            use-mypy: false
            use-isort: false
            extra-pylint-options: ""
            extra-pycodestyle-options: ""
            extra-flake8-options: ""
            extra-black-options: ""
            extra-mypy-options: ""
            extra-isort-options: ""
        - uses: docker/build-push-action@v1
          name: Build & push Docker image
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: pontostroy/web-render
            tag_with_ref: true
            tag_with_sha: true
